import Navbar from "@/components/Navbar";

export const metadata = {
  title: "My Blog",
  description: "Generated by create next app",
};

export default function BlogLayout({ children }) {
  return (
    <>
      <Navbar />
      <div className="max-w-4xl mx-auto">{children}</div>
    </>
  );
}
